name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main]
  pull_request_target:
    types: [closed]
    branches: [main]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          build: npm run build
          start: npm run start-prod
          wait-on: http://localhost:9000
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip')}}
      - name: Discord Webhook Notify
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        env:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          details: Deployed to https://github-action-test.onrender.com/
          severity: info
      - name: Discord Webhook Notify
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: failure()
        env:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          details: Error while deploying to https://github-action-test.onrender.com/
          severity: info
  tag_release:
    needs: [simple_deployment_pipeline]
    if: ${{ github.event.pull_request.merged == true && !contains(github.event.head_commit.message, '#skip') }}
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.merge_commit_sha }}
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.67.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
